pipeline:
  name: cicd-webDeployment
  identifier: cicdwebDeployment
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: hiteshsurya17flightdelay
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build Docker Image
                  identifier: Build_Docker_Image
                  spec:
                    connectorRef: DockerConnector
                    repo: hiteshsuryadevara130812/myapp
                    tags:
                      - latest
                    dockerfile: Dockerfile
                    context: .
              - step:
                  type: Run
                  name: Terraform Version Check
                  identifier: terraform_version_check
                  spec:
                    shell: Sh
                    image: hashicorp/terraform:1.5.7
                    command: |-
                      terraform --version
                      echo "Terraform is available"
              - step:
                  type: Run
                  name: Terraform apply
                  identifier: terraform_appyly
                  spec:
                    shell: Sh
                    image: hashicorp/terraform:1.5.7
                    command: |-
                      mkdir -p terraform && cd terraform

                      echo 'terraform {
                        required_providers {
                          random = {
                            source  = "hashicorp/random"
                            version = "~> 3.5"
                          }
                        }
                      }

                      provider "random" {}

                      resource "random_pet" "my_pet" {
                        length = 3
                      }' > main.tf

                      terraform init
                      terraform plan
                      terraform apply -auto-approve
        delegateSelectors:
          - macos-arm64
