pipeline:
  name: cicd-webDeployment
  identifier: cicdwebDeployment
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: hiteshsurya17flightdelay
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build Docker Image
                  identifier: Build_Docker_Image
                  spec:
                    connectorRef: DockerConnector
                    repo: hiteshsuryadevara130812/myapp
                    tags:
                      - latest
                    dockerfile: Dockerfile
                    context: .
              - step:
                  type: Run
                  name: Terraform Version Check
                  identifier: terraform_version_check
                  spec:
                    shell: Sh
                    image: hashicorp/terraform:1.5.7
                    command: |-
                      terraform --version
                      echo "Terraform is available"
        delegateSelectors:
          - macos-arm64
    - stage:
        name: terraform provisioning
        identifier: terraform_provisioning
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: Terraform Provisioning
                  identifier: terraform_provisioning_run
                  spec:
                    shell: Sh
                    image: hashicorp/terraform:1.5.7
                    command: |-
                      terraform --version
                      terraform init
                      terraform plan
                      terraform apply -auto-approve
                    workingDir: ./
                    envVariables:
                      TF_LOG: INFO
          delegateSelectors:
            - macos-arm64
