pipeline:
  name: cicd-webDeployment
  identifier: cicdwebDeployment
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: hiteshsurya17flightdelay
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build Docker Image
                  identifier: Build_Docker_Image
                  spec:
                    connectorRef: DockerConnector
                    repo: hiteshsuryadevara130812/myapp
                    tags:
                      - latest
                    dockerfile: Dockerfile
                    context: .
    - stage:
        name: terraform provisioning
        identifier: terraform_provisioning
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformApply
                  name: TerraformApply_1
                  identifier: TerraformApply_1
                  spec:
                    provisionerIdentifier: my_k8s_namespace
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            spec:
                              connectorRef: hiteshsurya17flightdelay
                              gitFetchType: Branch
                              branch: main
                              folderPath: .
                            type: Github
                  timeout: 10m
        tags: {}
        delegateSelectors:
          - macos-arm64
